language: ruby
rvm:
  - 2.3.1
matrix:
  include:
    - rvm: 2.2
      os: osx
      osx_image: xcode7.3
    - rvm: 2.3.1
      dist: trusty
      sudo: true
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CC=gcc-4.8; fi
  - bundle exec rake compile
cache: bundler
